### PR TITLE
C-API improvements

### PR DESCRIPTION
**Pull request by rehsack**
df1039f4 clogger: introduce custom loglevel manager
95824bce clogger: add reconfigure

### CODE REVIEW

**Comment by wilx** [comment]
What's the state of this?

**Comment by rehsack** [comment]
tested on linux and macos and both run fine - from my point of view it can be merged

**Comment by wilx** [comment]
It seems to freeze the Windows test: https://ci.appveyor.com/project/wilx/log4cplus/builds/20498962

**Comment by rehsack** [comment]
I don't see what fails.

**Comment by wilx** [comment]
I have merged https://github.com/wilx/log4cplus/tree/master-loglevel-manager into master.

**Pull request closed without merging**
