### PR TITLE
Added AppVeyor-CI for log4cplus

### PR DESCRIPTION
**Pull request by snikulov**
Added AppVeyor-CI for Log4cplus

After the merge, it is required to enable it in the service https://ci.appveyor.com

### CODE REVIEW

**Comment by snikulov** [comment]
@wilx have you registered project on AppVeyor site?

**Comment by wilx** [comment]
@snikulov I have registered https://ci.appveyor.com/project/wilx/log4cplus for log4cplus/log4cplus repository.

**Comment by snikulov** [comment]
@wilx ok. But log4plusorg should be better. At least it will check pull requests against org repo.

**Comment by wilx** [comment]
@snikulov I could not figure out how to do that. It adds the project to the authenticated user. The log4cplus organization on GitHub does not seem to be anyhow visible on AppVeyor.

**Comment by snikulov** [comment]
@wilx Well, you should write email message to appveyor support, as SOCI/curl project leaders does.

**Pull request merged**
